import { vol } from 'memfs'
import { vi, describe, it, expect, beforeEach, afterEach } from 'vitest'
import { runTypesGenerator } from '../src/types-generator'
import { resolve } from 'node:path'

vi.mock('fs/promises', async () => {
  const memfs = await vi.importActual<typeof import('memfs')>('memfs')
  return memfs.fs.promises
})
vi.mock('glob', () => ({ glob: vi.fn() }))
vi.mock('i18next-resources-for-ts', () => ({
  mergeResourcesAsInterface: vi.fn().mockReturnValue('export default interface Resources {}'),
}))

// The exact content runTypesGenerator writes to resourcesFile, given the mock above
const GENERATED_RESOURCES_CONTENT = `// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {}`

const makeConfig = () => ({
  locales: ['en'],
  extract: {
    input: ['src/'],
    output: 'locales/{{language}}/{{namespace}}.json',
    defaultNS: 'translation',
  },
  types: {
    input: ['locales/en/*.json'],
    output: 'src/types/i18next.d.ts',
    resourcesFile: 'src/types/resources.d.ts',
  },
})

describe('types-generator --ci (checkOnly mode)', () => {
  beforeEach(async () => {
    vol.reset()
    vi.clearAllMocks()

    const { glob } = await import('glob')
    ;(glob as any).mockResolvedValue(['/locales/en/translation.json'])
  })

  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('returns changed: false when resourcesFile is current and output exists', async () => {
    const config = makeConfig()
    const resourcesPath = resolve(process.cwd(), config.types.resourcesFile)
    const outputPath = resolve(process.cwd(), config.types.output)

    vol.fromJSON({
      '/locales/en/translation.json': JSON.stringify({ key: 'value' }),
      [resourcesPath]: GENERATED_RESOURCES_CONTENT,
      [outputPath]: '// user-edited declaration file',
    })

    const result = await runTypesGenerator(config as any, { checkOnly: true })

    expect(result).toEqual({ changed: false, changedFiles: [] })
  })

  it('returns changed: true with resourcesFile listed when its content differs', async () => {
    const config = makeConfig()
    const resourcesPath = resolve(process.cwd(), config.types.resourcesFile)
    const outputPath = resolve(process.cwd(), config.types.output)

    vol.fromJSON({
      '/locales/en/translation.json': JSON.stringify({ key: 'value' }),
      [resourcesPath]: '// outdated — does not match generated content',
      [outputPath]: '// user-edited declaration file',
    })

    const result = await runTypesGenerator(config as any, { checkOnly: true })

    expect(result.changed).toBe(true)
    expect(result.changedFiles).toContain(config.types.resourcesFile)
    expect(result.changedFiles).not.toContain(config.types.output)
  })

  it('returns changed: true with resourcesFile listed when it does not exist', async () => {
    const config = makeConfig()
    const outputPath = resolve(process.cwd(), config.types.output)

    vol.fromJSON({
      '/locales/en/translation.json': JSON.stringify({ key: 'value' }),
      [outputPath]: '// user-edited declaration file',
      // no resourcesFile
    })

    const result = await runTypesGenerator(config as any, { checkOnly: true })

    expect(result.changed).toBe(true)
    expect(result.changedFiles).toContain(config.types.resourcesFile)
    expect(result.changedFiles).not.toContain(config.types.output)
  })

  it('returns changed: true with output listed when it does not exist yet', async () => {
    const config = makeConfig()
    const resourcesPath = resolve(process.cwd(), config.types.resourcesFile)

    vol.fromJSON({
      '/locales/en/translation.json': JSON.stringify({ key: 'value' }),
      [resourcesPath]: GENERATED_RESOURCES_CONTENT,
      // no output file — first-time setup
    })

    const result = await runTypesGenerator(config as any, { checkOnly: true })

    expect(result.changed).toBe(true)
    expect(result.changedFiles).toContain(config.types.output)
    expect(result.changedFiles).not.toContain(config.types.resourcesFile)
  })

  it('lists both files when both are stale', async () => {
    const config = makeConfig()

    vol.fromJSON({
      '/locales/en/translation.json': JSON.stringify({ key: 'value' }),
      // neither file present
    })

    const result = await runTypesGenerator(config as any, { checkOnly: true })

    expect(result.changed).toBe(true)
    expect(result.changedFiles).toContain(config.types.resourcesFile)
    expect(result.changedFiles).toContain(config.types.output)
  })

  it('does not write any files to disk', async () => {
    const config = makeConfig()
    const resourcesPath = resolve(process.cwd(), config.types.resourcesFile)
    const outputPath = resolve(process.cwd(), config.types.output)

    vol.fromJSON({
      '/locales/en/translation.json': JSON.stringify({ key: 'value' }),
    })

    await runTypesGenerator(config as any, { checkOnly: true })

    expect(vol.existsSync(resourcesPath)).toBe(false)
    expect(vol.existsSync(outputPath)).toBe(false)
  })

  it('still writes files normally when checkOnly is not set', async () => {
    const config = makeConfig()
    const resourcesPath = resolve(process.cwd(), config.types.resourcesFile)

    vol.fromJSON({
      '/locales/en/translation.json': JSON.stringify({ key: 'value' }),
    })

    await runTypesGenerator(config as any)

    expect(vol.existsSync(resourcesPath)).toBe(true)
    const written = await vol.promises.readFile(resourcesPath, 'utf-8')
    expect(written).toBe(GENERATED_RESOURCES_CONTENT)
  })
})
